services:
  frontend:
    container_name: mce.surister.dev
    image: nginx
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=mce.surister.dev
      - NGINX_HOST=mce.surister.dev
    volumes:
      - ./dist/:/usr/share/nginx/html

networks:
  proxy:
    name: proxy
    external: true